#!/bin/bash
#cd opt/mssql
#lib/mssql-conf/checkinstall.sh
#lib/mssql-conf/checkrunninginstance.sh
if [ "$(ls -A /var/opt/mssql/data)" ]; then
	export ENV SA_PASSWORD=ZBEUqK7KxK
	opt/mssql/bin/mssql-conf set-sa-password
fi
