version: "3.4"

networks:
  agiper:
    external: true
  agiper_development:
    external: true
  agiper_testing:
    external: true
  agiper_staging:
    external: true
  agiper_production:
    external: true

volumes:
  agiper_mssql:
    name: agiper_mssql
    driver_opts:
      share: agiper-mssql
    driver: cloudstor:azure

services:
  # NGINX
  nginx:
    depends_on:
      - ghost
      - mssql
      - docker
      - teamcity
      - portainer
      - visualizer
    image: agiper/nginx
    networks:
      - agiper
      - agiper_testing
      - agiper_staging
      - agiper_production
      - agiper_development
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www
    deploy:
      resources:
        reservations:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# MSSQL
  mssql:
    image: agiper/mssql
    networks:
      - agiper
    ports:
      - "1433"
    volumes:
#      - agiper_mssql:/var/opt/mssql/data
      - ~/volume/mssql/data:/var/opt/mssql/data
    deploy:
      resources:
        reservations:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

  # DOCKER
  docker:
    image: agiper/docker
    networks:
      - agiper
    ports:
      - "5000:5000"
    volumes:
      - ~/volume/docker:/var/lib/registry    
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

  # TEAMCITY
  teamcity:
    depends_on:
      - mssql
    image: agiper/teamcity
    networks:
      - agiper
      - agiper_testing
      - agiper_staging
      - agiper_production
      - agiper_development
    ports:
      - "8111"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 4096M
        limits:
          cpus: '1.0'
          memory: 8192M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# PORTAINER
  portainer:
    image: agiper/portainer
    networks:
      - agiper
    ports:
      - "9000"
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# VISUALIZER
  visualizer:
    image: agiper/visualizer
    networks:
      - agiper
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper
