version: "3"

networks:
  agiper:
   external: true
  agiper_development:
   external: true

services:
  # MSSQL
  mssql:
    image: agiper/mssql
    networks:
      - agiper_development
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=$@_p@$$word
    volumes:
      - ~/volume/mssql:/var/opt/mssql
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # REDIS
  redis:
    image: agiper/redis
    networks:
      - agiper_development
    ports:
      - "6379"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none          
      placement:
        constraints: [node.role == manager]

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq
    networks:
      - agiper_development
    ports:
      - "5672"
      - "15672"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]
  
  # ELASTIC
  elastic:
    image: agiper/elastic
    networks:
      - agiper_development
    ports:
      - "5601"
      - "9200"
      - "9300"
    environment:
      - http.host=0.0.0.0
      - cluster.name=agiper
      - node.name=development
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

  #WEBHOST
  webhost:
    image: agiper/dotnet
    networks:
      - agiper_development
    ports:
      - "80"
    environment:
      - APPLICATION=Rolene.Server.Host.Web.dll
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

  #APIHOST
  apihost:
    image: agiper/dotnet
    networks:
      - agiper_development
    ports:
      - "81"
    environment:
      - APPLICATION=Rolene.Server.Host.Api.dll
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]
  
  #JOBHOST
  jobhost:
    image: agiper/dotnet
    networks:
      - agiper_development
    ports:
      - "82"
    environment:
      - APPLICATION=Rolene.Server.Host.Job.dll
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]