version: "3"

networks:
  agiper:
   external: true

services:
  # NGINX
  nginx:
    image: agiper/nginx
    networks:
      - agiper
    ports:
      - "80:80"
    volumes:
      - ~/volume/nginx:/etc/nginx
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

 # SWARM
  swarm:
    image: agiper/swarm
    networks:
      - agiper
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # GHOST
  ghost:
    image: agiper/ghost
    networks:
      - agiper
    ports:
      - "2368"
    volumes: 
      - ~/volume/ghost:/var/lib/ghost
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # DOCKER
  docker:
    image: agiper/docker
    networks:
      - agiper
    ports:
      - "5000:5000"
    volumes:
      - ~/volume/docker:/var/lib/registry
    environment:
      - REGISTRY_HTTP_TLS_KEY=/var/lib/registry/docker.key
      - REGISTRY_HTTP_TLS_CERTIFICATE=/var/lib/registry/docker.crt
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # TEAMCITY
  teamcity:
    image: agiper/teamcity
    networks:
      - agiper
    ports:
      - "8111"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]