version: "3.4"

networks:
  development:
    external: true

services:

  #WEB
  web:
    image: localhost:5000/development/quorum_web
    networks:
      development:
        aliases:
          - development_quorum_web
    ports:
      - "80"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #API
  api:
    image: localhost:5000/development/quorum_api
    networks:
      development:
        aliases:
          - development_quorum_api
    ports:
      - "81"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated    
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

 #FUND
  fund:
    image: localhost:5000/development/quorum_fund
    networks:
      development
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

#ORDER
  order:
    image: localhost:5000/development/quorum_order
    networks:
      development
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #MARKET
  market:
    image: localhost:5000/development/quorum_market
    networks:
      development
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development
