version: "3.4"

networks:
  development:
    external: true

services:
  # WATCHTOWER
  watchtower:
    command: --interval 30
    image: containrrr/watchtower
    networks:
      - development
    environment:
      - ENVIRONMENT=development
    volumes:
      - /root/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 32M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

  #WEB
  service_web:
    image: localhost:5000/development/quorum_service_web
    networks:
      development:
        aliases:
          - development_quorum_service_web
    ports:
      - "80"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

  #API
  service_api:
    image: localhost:5000/development/quorum_service_api
    networks:
      development:
        aliases:
          - development_quorum_service_api
    ports:
      - "81"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

#SSE
  service_sse:
    image: localhost:5000/development/quorum_service_sse
    networks:
      development:
        aliases:
          - development_quorum_service_sse
    ports:
      - "82"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

 #BANK
  endpoint_bank:
    image: localhost:5000/development/quorum_endpoint_bank
    networks:
      development:
        aliases:
          - development_quorum_endpoint_bank
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M      
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

 #FUND
  endpoint_fund:
    image: localhost:5000/development/quorum_endpoint_fund
    networks:
      development:
        aliases:
          - development_quorum_endpoint_fund
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M      
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

#TRADE
  endpoint_trade:
    image: localhost:5000/development/quorum_endpoint_trade
    networks:
      development:
        aliases:
          - development_quorum_endpoint_trade
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M      
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

  #MARKET
  endpoint_market:
    image: localhost:5000/development/quorum_endpoint_market
    networks:
      development:
        aliases:
          - development_quorum_endpoint_market
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M      
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development
