version: "3.4"

networks:
  development:
    external: true

services:
  # REDIS
  redis:
    image: agiper/redis:latest
    networks:
      - development
    ports:
      - "6379"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

  # RAVENDB
  ravendb:
    image: agiper/ravendb:latest
    networks:
      - development
    ports:
      - "8080"
      - "38888"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

  # ELASTIC
  elastic:
    image: agiper/elastic:latest
    networks:
      - development
    ports:
      - "5601"
      - "9200"
      - "9300"
    environment:
      - ENVIRONMENT=development
      - "cluster.name=development"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    deploy:
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development


  # STELLAR
  stellar:
    image: agiper/stellar:latest
    networks:
      - development
    ports:
      - "8000"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq:latest
    networks:
      - development
    ports:
      - "5672"
      - "15672"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.environment == development
