version: "3.4"

networks:
  development:
    external: true

services:
  
  # MSSQL
  mssql:
    image: agiper/mssql:latest
    networks:
      - development
    ports:
      - "1433"
    environment:
      - ENVIRONMENT=development
    volumes:
       - ~/volume/mssql/data:/var/opt/mssql/data
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # REDIS
  redis:
    image: agiper/redis:latest
    networks:
      - development
    ports:
      - "6379"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # ELASTIC
  elastic:
    image: agiper/elasticsearch:latest
    networks:
      - development
    ports:
      - "5601"
      - "9200"
      - "9300"
    environment:
      - ENVIRONMENT=development
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=rolene_development"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 8192M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development


  # STELLAR
  stellar:
    image: agiper/stellar:latest
    networks:
      - development
    ports:
      - "8000"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq:latest
    networks:
      - development
    ports:
      - "5672"
      - "15672"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development
