#!/bin/bash

echo -e "\e[1;32m[1/2] Removing overlay networks\e[0m"
docker stack down agiper
docker stack down rolene_development

echo -e "\e[1;32m[2/2] Removing stacks from swarm\e[0m"
docker network rm agiper
docker network rm rolene_development
