version: "3"

networks:
  agiper:

services:
  # MSSQL
  mssql:
    image: agiper/mssql
    volumes:
      - ~/volume/mssql:/var/lib/mssql
    entrypoint: service mssql start && bash
    networks:
      - agiper
    ports:
      - "1433"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M    
      placement:
        constraints: [node.role == manager]

  # REDIS
  redis:
    image: agiper/redis
    entrypoint: redis-server /etc/redis/redis.conf
    networks:
      - agiper
    ports:
      - "6379"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      placement:
        constraints: [node.role == manager]

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq
    entrypoint: rabbitmq-server
    networks:
      - agiper
    ports:
      - "5672"
      - "15672"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M    
      placement:
        constraints: [node.role == manager]
  
  # ELASTICSEARCH
  elasticsearch:
    image: agiper/elasticsearch    
    entrypoint: service elasticsearch start && bash
    networks:
      - agiper
    ports:
      - "5601"
      - "9200"
      - "9300"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.75'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M

  #DOTNET
  dotnet:
    image: agiper/dotnet
    volumes:
      - ~/volume/dotnet:/var/lib/dotnet
    entrypoint: dotnet $EXECUTABLE && bash
    networks:
      - agiper
    ports:
      - "80"
    depends_on:
      - mssql
      - redis
      - rabbitmq
      - elasticsearch
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        delay: 5s
        window: 120s
        max_attempts: 3
        condition: on-failure
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue