version: "3"

networks:
  agiper:

services:
  # MSSQL
  mssql:
    image: agiper/mssql
    volumes:
      - ~/volume/mssql:/var/opt/mssql
    environment:
      - SA_PASSWORD=sa
    entrypoint: /opt/mssql/bin/sqlservr-setup --accept-eula --set-sa-password --start-service
    networks:
      - agiper
    ports:
      - "1433"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # REDIS
  redis:
    image: agiper/redis
    networks:
      - agiper
    ports:
      - "6379"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none          
      placement:
        constraints: [node.role == manager]

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq
    networks:
      - agiper
    ports:
      - "5672"
      - "15672"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]
  
  # ELASTIC
    image: agiper/elastic
    environment:
      - cluster.name=agiper
      - node.name=development
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    entrypoint: /usr/local/bin/elastic.sh
    networks:
      - agiper
    ports:
      - "5601"
      - "9200"
      - "9300"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  #WEBHOST
  webhost:
    image: agiper/dotnet
    volumes:
      - ~/volume/dotnet/web:/var/lib/dotnet
    entrypoint: dotnet /var/lib/dotnet/Rolene.Server.Host.Web.dll
    networks:
      - agiper
    ports:
      - "8080"
    depends_on:
      - mssql
      - redis
      - elastic
      - rabbitmq
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

  #APIHOST
  apihost:
    image: agiper/dotnet
    volumes:
      - ~/volume/dotnet/api:/var/lib/dotnet
    entrypoint: dotnet /var/lib/dotnet/Rolene.Server.Host.Api.dll
    networks:
      - agiper
    ports:
      - "8081"
    depends_on:
      - mssql
      - redis
      - elastic
      - rabbitmq
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]
  
  #JOBHOST
  jobhost:
    image: agiper/dotnet
    volumes:
      - ~/volume/dotnet/job:/var/lib/dotnet
    entrypoint: dotnet /var/lib/dotnet/Rolene.Server.Host.Job.dll
    networks:
      - agiper
    ports:
      - "8082"
    depends_on:
      - mssql
      - redis
      - elastic
      - rabbitmq
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]