version: "3.7"

networks:
  testing:
    external: true
  staging:
    external: true
  production:
    external: true
  development:
    external: true
  infrastructure:
    external: true

services:
  # NGINX
  nginx:
    image: agiper/nginx
    networks:
      - testing
      - staging
      - production
      - development
      - infrastructure
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

# MSSQL
  mssql:
    image: agiper/mssql
    networks:
      - infrastructure
    ports:
      - "1433"
    volumes:
      - ~/volume/mssql/data/infrastructure:/var/opt/mssql/data
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

  # DOCKER
  docker:
    image: agiper/docker
    networks:
      - infrastructure
    ports:
      - "5000:5000"
    volumes:
      - ~/volume/docker:/var/lib/registry
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

  # TEAMCITY
  teamcity:
    image: agiper/teamcity
    networks:
      - infrastructure
    ports:
      - "8111"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

# PORTAINER
  portainer:
    image: agiper/portainer
    networks:
      - infrastructure
    ports:
      - "9000"
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager

# VISUALIZER
  visualizer:
    image: agiper/visualizer
    networks:
      - infrastructure
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
