version: "3.4"

networks:
  testing:
    external: true
  staging:
    external: true
  production:
    external: true
  development:
    external: true
  infrastructure:
    external: true
  
services:
  # NGINX
  nginx:
    depends_on:
      - ghost
      - mssql
      - docker
      - teamcity
      - portainer
      - visualizer
    image: agiper/nginx:latest
    networks:
      - testing
      - staging
      - production
      - development
      - infrastructure
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    volumes:
      - ~/volume/nginx:/etc/nginx
      - ~/volume/nginx/www:/etc/nginx/www
    deploy:
      resources:
        reservations:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# MSSQL
  mssql:
    image: agiper/mssql:latest
    networks:
      - testing
      - staging
      - production
      - development    
      - infrastructure
    ports:
      - "1433"
    volumes:
      - ~/volume/mssql/data:/var/opt/mssql/data
    deploy:
      resources:
        reservations:
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

  # DOCKER
  docker:
    image: agiper/docker:latest
    networks:
      - infrastructure
    ports:
      - "5000:5000"
    volumes:
      - ~/volume/docker:/var/lib/registry    
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

  # TEAMCITY
  teamcity:
    depends_on:
      - mssql
    image: agiper/teamcity:latest
    networks:
      - infrastructure
    ports:
      - "8111"
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 4096M
        limits:
          cpus: '1.0'
          memory: 8192M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# PORTAINER
  portainer:
    image: agiper/portainer:latest
    networks:
      - infrastructure
    ports:
      - "9000"
    volumes:
      - ~/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper

# VISUALIZER
  visualizer:
    image: agiper/visualizer:latest
    networks:
      - infrastructure
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.hostname == agiper
