#!/bin/bash
echo -e "\e[1;32m[1/2] Initializing cluster\e[0m"
docker swarm init --advertise-addr 52.187.186.27

echo -e "\e[1;32m[2/2] Creating overlay networks\e[0m"
docker network create --driver overlay --subnet 10.0.0.0/24 agiper
docker network create --driver overlay --subnet 10.1.1.0/24 rolene_development
docker network create --driver overlay --subnet 10.1.2.0/24 rolene_testing
docker network create --driver overlay --subnet 10.1.3.0/24 rolene_staging
docker network create --driver overlay --subnet 10.1.4.0/24 rolene_production