#!/bin/bash
echo -e "\e[1;32m[1/3] Initializing cluster\e[0m"
docker swarm init --advertise-addr 52.187.186.27

echo -e "\e[1;32m[2/3] Creating overlay networks\e[0m"
docker network create --driver overlay --subnet 10.0.0.0/24 agiper
docker network create --driver overlay --subnet 10.1.1.0/24 agiper_development
docker network create --driver overlay --subnet 10.2.2.0/24 agiper_testing
docker network create --driver overlay --subnet 10.3.3.0/24 agiper_staging
docker network create --driver overlay --subnet 10.4.4.0/24 agiper_production

echo -e "\e[1;32m[3/3] Mount Azure storage volume\e[0m"
docker plugin install docker4x/cloudstor:17.06.0-ce-rc3-azure1 \
  --alias cloudstor:azure \
  --grant-all-permissions \
  CLOUD_PLATFORM=AZURE \
  AZURE_STORAGE_ACCOUNT="agiper" \
  AZURE_STORAGE_ACCOUNT_KEY="3xpWfWxxyAo3MZW/WhPmv4Q/VWiutOU2u4SLKoLzltRA8KR+MyVthM1PmHCMAvdvSie3Dw41r137b0FTZoWS6Q=="
docker volume create agiper_development --driver=cloudstor:azure

