version: "3.4"

networks:
  agiper_development:
    external: true

services:
  
  #WEB
  web:
    image: localhost:5000/quorum_development/web
    networks:
      agiper_development:
        aliases:
          - quorum_development_web
    ports:
      - "8080"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #API
  api:
    image: localhost:5000/quorum_development/api
    networks:
      agiper_development:
        aliases:
          - quorum_development_api
    ports:
      - "8081"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #JOB
  job:
    image: localhost:5000/quorum_development/job
    networks:
      agiper_development:
        aliases:
          - quorum_development_job
    ports:
      - "8082"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #ASSET
  asset:
    image: localhost:5000/quorum_development/asset
    networks:
      agiper_development:
        aliases:
          - quorum_development_asset
    ports:
      - "8083"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

#EXCHANGE
  exchange:
    image: localhost:5000/quorum_development/exchange
    networks:
      agiper_development:
        aliases:
          - quorum_development_exchange
    ports:
      - "8084"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development
