version: "3"

networks:
  agiper:

services:
  # NGINX
  nginx:
    image: agiper/nginx
    volumes:
      - ~/volume/nginx:/etc/nginx
    entrypoint: nginx -g 'daemon off;'
    networks:
      - agiper
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  # GHOST
  ghost:
    image: ghost
    volumes:
      - ~/volume/ghost:/var/lib/ghost
    networks:
      - agiper
    ports:
      - "2368"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none          
      placement:
        constraints: [node.role == manager]              

  # TEAMCITY
  teamcity:
    image: agiper/teamcity
    volumes:
      - ~/volume/teamcity:/var/lib/teamcity
    entrypoint: /opt/teamcity/bin/teamcity-server.sh run
    networks:
      - agiper
    ports:
      - "8111"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
      restart_policy:
        condition: none          
      placement:
        constraints: [node.role == manager]