version: "3.4"

networks:
  agiper_development:
    external: true

services:

  #WEB
  web:
    image: localhost:5000/quorum_development/web
    networks:
      agiper_development:
        aliases:
          - quorum_development_web
    ports:
      - "80"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #API
  api:
    image: localhost:5000/quorum_development/api
    networks:
      agiper_development:
        aliases:
          - quorum_development_api
    ports:
      - "81"
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated    
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

 #FUND
  fund:
    image: localhost:5000/quorum_development/fund
    networks:
      agiper_development:
        aliases:
          - quorum_development_fund
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

#ORDER
  order:
    image: localhost:5000/quorum_development/order
    networks:
      agiper_development:
        aliases:
          - quorum_development_order
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #MARKET
  market:
    image: localhost:5000/quorum_development/market
    networks:
      agiper_development:
        aliases:
          - quorum_development_market
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        delay: 1m
        window: 1m
        condition: any
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development
