version: "3"

networks:
  agiper:
   external: true
  rolene_development:
   external: true

services:
  
  # **************** INFRASTRUCTURE *****************

  # MSSQL
  mssql:
    image: agiper/mssql
    networks:
      - agiper
      - rolene_development
    ports:
      - "1433"
    environment:
      - SA_PASSWORD=rX2Ja!293F8@
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02

  # REDIS
  redis:
    image: agiper/redis
    networks:
      - agiper
      - rolene_development
    ports:
      - "6379"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        condition: none          
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02

  # ELASTIC
  elastic:
    image: agiper/elastic
    networks:
      - agiper
      - rolene_development
    ports:
      - "5601"
      - "9200"
      - "9300"
    environment:
      - http.host=0.0.0.0
      - cluster.name=agiper
      - node.name=development
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq
    networks:
      - agiper
      - rolene_development
    ports:
      - "5672"
      - "15672"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02
  
  # ****************** SERVICES *******************

  #WEBHOST
  webhost:
    image: docker:5000/rolene/webhost
    networks:
      - agiper
      - rolene_development
    ports:
      - "80"
    environment:
      - APPLICATION=Rolene.Server.Host.Web.dll
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.75'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02

  #APIHOST
  apihost:
    image: docker:5000/rolene/apihost
    networks:
      - agiper
      - rolene_development
    ports:
      - "81"
    environment:
      - APPLICATION=Rolene.Server.Host.Api.dll
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.75'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02
  
  #JOBHOST
  jobhost:
    image: docker:5000/rolene/jobhost
    networks:
      - agiper
      - rolene_development
    ports:
      - "82"
    environment:
      - APPLICATION=Rolene.Server.Host.Job.dll
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.75'
          memory: 1024M
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
          - node.hostname == agiper-node02