version: "3"

networks:
  rolene_development:
    external: true
  rolene_testing:
    external: true
  rolene_staging:
    external: true
  rolene_production:
    external: true

services:
  
  # **************** INFRASTRUCTURE *****************

  # MSSQL
  mssql:
    image: agiper/mssql
    networks:
      - rolene_development
    ports:
      - "1433"
    environment:
      - ENVIRONMENT=development
    volumes: 
      - ~/volume/mssql/data:/var/opt/mssql/data
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # REDIS
  redis:
    image: agiper/redis
    networks:
      - rolene_development
    ports:
      - "6379"
    deploy:
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # RABBITMQ
  rabbitmq:
    image: agiper/rabbitmq
    networks:
      - rolene_development
    ports:
      - "5672"
      - "15672"
    environment:
      - ENVIRONMENT=development
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 4096M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

 # ELASTICSEARCH
  elasticsearch:
    image: agiper/elasticsearch
    networks:
      - rolene_development
    ports:
      - "5601"
      - "9200"
      - "9300"
    environment:
      - ENVIRONMENT=development
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.name=rolene_development"
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 1024M
        limits:
          cpus: '0.75'
          memory: 8192M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  # ****************** SERVICES *******************

#WEBHOST
  webhost:
    depends_on:
      - mssql
      - redis
      - rabbitmq
      - elasticsearch
    image: localhost:5000/rolene_development/webhost
    networks:
      rolene_development:
        aliases:
          - rolene_development_webhost
    ports:
      - "8080"
    environment:
      - ENVIRONMENT=development
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development

  #APIHOST
  apihost:
    depends_on:
      - mssql
      - redis
      - rabbitmq
      - elasticsearch
    image: localhost:5000/rolene_development/apihost
    networks:
      rolene_development:
        aliases:
          - rolene_development_apihost
    ports:
      - "8081"
    environment:
      - ENVIRONMENT=development
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development
  
  #JOBHOST
  jobhost:
    depends_on:
      - mssql
      - redis
      - rabbitmq
      - elasticsearch
    image: localhost:5000/rolene_development/jobhost
    networks:
      rolene_development:
        aliases:
          - rolene_development_jobhost
    ports:
      - "8082"
    environment:
      - ENVIRONMENT=development
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2048M
      restart_policy:
        delay: 5m
        window: 1m
        condition: on-failure
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue
      placement:
        constraints:
          - node.role == worker
          - node.labels.environment == development