version: "3"

networks:
    net:

services:
  # REDIS
  redis:
    networks:
      - net
    ports:
      - 6379
    resources:
      reservations:
        cpus: '0.25'
        memory: 1024M
    image: agiper/redis        
    deploy:
      placement:
        constraints: [node.role == manager]
  

# MSSQL
  mssql:
    networks:
      - net
    ports:
      - 1433
    resources:
      reservations:
        cpus: '0.25'
        memory: 1024M
    image: agiper/mssql        
    deploy:
      placement:
        constraints: [node.role == manager]

  
  # RABBITMQ
  rabbitmq:
    networks:
      - net
    ports:
      - 5672
      - 15672
    resources:
      reservations:
        cpus: '0.25'
        memory: 1024M
    image: agiper/rabbitmq
    deploy:
      placement:
        constraints: [node.role == manager]

  
  # ELASTIC
  elastic:
  networks:
      - net
    ports:
      - 5601
      - 9200
      - 9300
    resources:
      limits:
        cpus: '0.75'
        memory: 2048M
      reservations:
        cpus: '0.25'
        memory: 1024M
    deploy:
      replicas: 2
      mode: replicated
    image: agiper/elastic


  #DOTNET
  dotnet:
    networks:
      - net
    ports:
      - 80
    image: agiper/dotnet
    depends_on:
      - redis
      - elastic
      - rabbitmq
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        delay: 5s
        window: 120s
        max_attempts: 3
        condition: on-failure
      update_config:
        delay: 10s
        monitor: 60s
        parallelism: 1
        max_failure_ratio: 0.3
        failure_action: continue