#!/bin/bash

echo -e "\n\e[1;32m[1/3] Setting kernel parameters\e[0m"
sudo sysctl vm.overcommit_memory=1
sudo sysctl -w vm.max_map_count=262144

echo -e "\n\e[1;32m[2/3] Creating overlay networks\e[0m"
docker network create --driver overlay --subnet 10.0.0.0/24 agiper
docker network create --driver overlay --subnet 10.0.1.0/24 agiper_development

echo -e "\n\e[1;32m[3/3] Deploying stacks to swarm\e[0m"
docker stack deploy -c agiper.yml agiper
docker stack deploy -c agiper_development.yml agiper_development
