#!/bin/bash
docker system prune
docker build -t agiper/base agiper-base/
docker build -t agiper/tool agiper-tool/
docker build -t agiper/nginx agiper-nginx/
docker build -t agiper/redis agiper-redis/
docker build -t agiper/mssql agiper-mssql/
docker build -t agiper/dotnet agiper-dotnet/
docker build -t agiper/elastic agiper-elastic/
docker build -t agiper/rabbitmq agiper-rabbitmq/
docker build -t agiper/teamcity agiper-teamcity/
