#!/bin/bash
docker build -t agiper/base agiper-base/
docker build -t agiper/java agiper-java/
docker build -t agiper/tool agiper-tool/
docker build -t agiper/nginx agiper-nginx/
docker build -t agiper/redis agiper-redis/
docker build -t agiper/mssql agiper-mssql/
docker build -t agiper/docker agiper-docker/
docker build -t agiper/dotnet agiper-dotnet/
docker build -t agiper/stellar agiper-stellar/
docker build -t agiper/rabbitmq agiper-rabbitmq/
docker build -t agiper/teamcity agiper-teamcity/
docker build -t agiper/portainer agiper-portainer/
docker build -t agiper/visualizer agiper-visualizer/
docker build -t agiper/elasticsearch agiper-elasticsearch/
